language: node_js
node_js:
  - "12.6.0"
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6
      - postgresql-client-9.6
env:
  global:
    - PGPORT=5432
    - PGUSER=postgres
    - PGHOST=localhost
    - PGDATABASE=postgres
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database postgres;' -U postgres
script: npm test