name: npm test

on:
  push:
    branches-ignore:
      - master
      - master_temp
  pull_request:
    branches-ignore:
      - master
      - master_temp

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        postgres-version: [9.6]
        node-version: [12.x, 13.x]

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
          PGHOST: localhost
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          PGDATABASE: postgres
          CI: true
